# Generated by Django 6.1.1 on 2026-09-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='latitude',
            field=models.FloatField(default=33.6844),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='longitude',
            field=models.FloatField(default=73.0479),
        ),
        migrations.AddField(
            model_name='resource',
            name='latitude',
            field=models.FloatField(default=33.6844),
        ),
        migrations.AddField(
            model_name='resource',
            name='longitude',
            field=models.FloatField(default=73.0479),
        ),
    ]
