# Generated by Django 6.1.1 on 2026-09-26 01:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resource_responder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dispatchlog',
            options={'ordering': ['-dispatched_at']},
        ),
        migrations.AlterModelOptions(
            name='helprequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dispatchlog',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, help_text='Dispatcher Admin/Command Official', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchlog',
            name='notes',
            field=models.TextField(blank=True, help_text='Special instructions for field taskforce', null=True),
        ),
        migrations.AddField(
            model_name='dispatchlog',
            name='quantity_allocated',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='disaster_type',
            field=models.CharField(choices=[('flood', 'Flash Flood Evacuation'), ('medical', 'Medical Emergency / Casualty'), ('ration', 'PM Food & Water Supply'), ('collapse', 'Structural Collapse Rescue')], default='flood', max_length=50),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='people_affected',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='tracking_code',
            field=models.CharField(blank=True, help_text='Unique PM Relief Tracking ID', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='victim_name',
            field=models.CharField(default='Unknown', help_text='Citizen Name / Contact Person', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='depot_name',
            field=models.CharField(default='Central Depot Sahiwal', max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='quantity',
            field=models.PositiveIntegerField(default=100, help_text='Current available items/units'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(default='Untitled Resource', help_text='e.g. Sahiwal Relief Warehouse Pack-A', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='total_capacity',
            field=models.PositiveIntegerField(default=500, help_text='Total capacity of depot'),
        ),
        migrations.AddField(
            model_name='resource',
            name='unit_type',
            field=models.CharField(default='Packs', help_text='e.g. Packs, Liters, Boats, Kits', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispatchlog',
            name='help_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='core.helprequest'),
        ),
        migrations.AlterField(
            model_name='dispatchlog',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='core.resource'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='latitude',
            field=models.FloatField(default=30.6682),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='location',
            field=models.CharField(help_text='City, Sector, or Landmark', max_length=255),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='longitude',
            field=models.FloatField(default=73.1114),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='need_type',
            field=models.CharField(help_text='e.g. 15 Stranded, Medical Kit needed', max_length=100),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Dispatch'), ('matched', 'Matched With Unit'), ('dispatched', 'Rescue Unit Dispatched'), ('completed', 'Evacuated / Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Level 1 Critical')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='victim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='latitude',
            field=models.FloatField(default=30.6682),
        ),
        migrations.AlterField(
            model_name='resource',
            name='longitude',
            field=models.FloatField(default=73.1114),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('food', 'PM Food Ration Packs'), ('water', 'Clean Drinking Water'), ('medical', 'Medical Emergency Team / Kits'), ('rescue_boat', 'Rescue Boats & Life Vests'), ('shelter', 'Temporary Relief Tents'), ('helicopter', 'Aerial Air-Drop Unit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('available', 'Available in Warehouse'), ('in_use', 'Partially Dispatched'), ('dispatched', 'Fully Dispatched'), ('depleted', 'Out of Stock')], default='available', max_length=20),
        ),
    ]
