# Generated by Django 6.1.1 on 2026-09-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dispatchlog_options_alter_helprequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helprequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='dispatchlog',
            name='dispatched_by',
        ),
        migrations.RemoveField(
            model_name='dispatchlog',
            name='help_request',
        ),
        migrations.RemoveField(
            model_name='dispatchlog',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='dispatchlog',
            name='quantity_allocated',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='disaster_type',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='people_affected',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='tracking_code',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='victim',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='depot_name',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='responder',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='status',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='total_capacity',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(db_column='name', default='General Resource', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispatchlog',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='need_type',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='urgency',
            field=models.CharField(default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='victim_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterModelTable(
            name='helprequest',
            table='victim_help_requests',
        ),
        migrations.AlterModelTable(
            name='resource',
            table='resource_depots',
        ),
    ]
