# Generated by Django 6.1.1 on 2026-09-30 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_helprequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchlog',
            name='help_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.helprequest'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(default='General Resource', max_length=100),
        ),
    ]
