# Generated by Django 6.1.1 on 2026-09-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dispatchlog_help_request_alter_helprequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchlog',
            name='help_request',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.helprequest'),
        ),
        migrations.AlterField(
            model_name='dispatchlog',
            name='resource',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='core.resource'),
        ),
    ]
