# Generated by Django 6.1.1 on 2026-09-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dispatchlog_help_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchlog',
            name='resource',
        ),
        migrations.AddField(
            model_name='dispatchlog',
            name='action_by',
            field=models.CharField(default='System', max_length=100),
        ),
        migrations.AddField(
            model_name='dispatchlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchlog',
            name='resource_name',
            field=models.CharField(default='Resource Allocated', max_length=100),
        ),
        migrations.AddField(
            model_name='dispatchlog',
            name='status_update',
            field=models.CharField(default='DISPATCHED', max_length=50),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='admin_instructions',
            field=models.TextField(blank=True, default='No special instructions', null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='allocated_resource',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='assigned_responder',
            field=models.CharField(blank=True, default='Unassigned', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='progress_notes',
            field=models.TextField(blank=True, default='Awaiting responder dispatch', null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='depot_location',
            field=models.CharField(default='Central Depot, Sahiwal', max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED_TO_RESPONDER', 'Assigned to Responder'), ('DISPATCHED', 'Dispatched / En Route'), ('ON_SCENE', 'On Scene'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
    ]
