# Generated by Django 6.1.1 on 2026-09-30 16:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_dispatchlog_resource_dispatchlog_action_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dispatchlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='depot_location',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_available',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed emergency description', null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='victim_phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='current_location',
            field=models.CharField(default='Central Station', max_length=200),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(default='EQUIPMENT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Deployed / Busy'), ('MAINTENANCE', 'Off Service')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispatchlog',
            name='action_by',
            field=models.CharField(default='System Administrator', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispatchlog',
            name='dispatched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dispatchlog',
            name='help_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.helprequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispatchlog',
            name='resource_name',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchlog',
            name='status_update',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='admin_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='allocated_resource',
            field=models.CharField(blank=True, default='None', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='assigned_responder',
            field=models.CharField(blank=True, default='Unassigned', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='latitude',
            field=models.FloatField(default=30.6514),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='location',
            field=models.CharField(help_text='Street / Area Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='longitude',
            field=models.FloatField(default=73.1306),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='need_type',
            field=models.CharField(choices=[('Medical Emergency', 'Medical Emergency / Ambulance'), ('Flood Relief', 'Flood Relief / Water Rescue'), ('Fire Emergency', 'Fire Emergency'), ('Food & Shelter', 'Food, Water & Shelter Request'), ('Earthquake Rescue', 'Earthquake Building Collapse'), ('General Rescue', 'General Rescue / Hazmat')], default='Medical Emergency', max_length=100),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='progress_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('ASSIGNED_TO_DEPT', 'Assigned to Field Department'), ('IN_PROGRESS', 'Responder & Resource Deployed'), ('RESOLVED', 'Completed & Safely Resolved'), ('REJECTED', 'Cancelled / Invalid Alert')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low - Informational'), ('medium', 'Medium - Urgent Needs'), ('high', 'High - Severe Situation'), ('critical', 'CRITICAL - Life Threatening')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='victim_name',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='helprequest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='resource',
            table=None,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='resource',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.department'),
        ),
    ]
